### ISSUE TITLE
using '-result_as'

### ISSUE THREAD

**Issue by ialarmedalien** [damil/DBIx-DataModel#17]
When is it possible to use `-result_as` with `select` queries?

My use case: I create a statement object with an initial set of parameters and then add further `-where` parameters according to the values of some filters using `$statement->refine`. The last step is to output the results; depending on the type of output required, I might want a statement handle (`-result_as => $sth`) or a `DBIx::DataModel::Statement` object, i.e.

```
my $stt = $self->schema( $schema )->table( $table )->select( %args );
...
$stt->refine( -where => %where_args );
...
# ready to output
if ( $format eq 'csv' ) {
	# use a statement handle
	my $sth = ???; # !! is this possible?
#	output as CSV
#	$csv->print( $io, $sth->{NAME_lc} );
# 	...
}
else {
	# use DBIx::DataModel::Statement object
	...
}
```
Once I've created the initial $stt object, it is in status `refined` and I can only add more `-where` args at this point. If I try running `$stt->reset` I can get back to status `new` but adding the old arguments with `-result_as => 'sth'` still leaves me with a `DBIx::DataModel::Statement` object, not the statement handle that I'd like to use.

It's really useful to be able to call `$stt->refine` to add parameters to an existing query. Is there any way to get a DBI statement handle out of the `DBIx::DataModel::Statement` object?

**Comment by damil** [comment]
> When is it possible to use -result_as with select queries? 

Always, as long as you have a pointer to a statement object, or when you start a new statement from a datasource object.

> Is there any way to get a DBI statement handle out of the DBIx::DataModel::Statement object? 

Sure, just call the select() method again, and specify which kind of result you want.


my $stt = $self->schema( $schema )->table( $table )->select( %args );
...
$stt->refine( -where => %where_args );
...
my $sth = $stt->select(-result_as => 'sth');

**Comment by ialarmedalien** [comment]
Thank you -- it wasn't totally clear from the docs that running `$stt->select()` again would preserve the previous arguments.

**Comment by ialarmedalien** [comment]
Running into another problem when trying to use the same statement object for a number of things. I'd like to do the following:

* get a total row count, `$stt->row_count`
* set the page size and current page (if applicable)
* retrieve those results
* get a statement handle, `$sth`, to retrieve the column names

I can't seem to work out a way of doing this, and it's not really clear to me what's going on with `$stt->select()` and the different `$stt->status`es.

One of many variations I've tried that doesn't work:
```
	my $stt = $self->get_statement( $args );
	my $total = $stt->row_count;
	...
	$stt->refine( -page_size => $self->page_size, -page_index => $self->page_index );
	...
	my $results = $stt->all;
	my $sth = $stt->select( -result_as => 'sth' );
	my $cols = $sth->{NAME_lc};
```

Thanks in advance for any help. It would be really useful if some examples like this were added to the documentation.

**Comment by damil** [comment]
Hum ... I'm afraid the API is not exactly well-suited for your use case. 
I should probably add some direct accessors for the sth and for the 
{NAME} attribute.

The row_count() method needs to produce the SQL so that it can generate 
another sql request to the database using SELECT count(*) FROM ...

But then, since the SQL has already been generated, it's too late to 
specify limit/offset or -page_size/-page_index.

I would suggest to go like this :

a) store your -where criteria in a hash

b) make a first call to $source->select(-where => \%criteria, 
-result_as=>'statement')->row_count

c) create a 2nd statement my $stt = $source->select(-where => 
\%criteria, -result_as=>'statement')

d) retrieve  my $page_rows = $stt->select(-page_index => 3, -page_size 
=> 10);

e) to get the column names, you can just look at keys %{$page_rows->[0]};

f) or alternatively you can go to the internal sth attribute 
$stt->{sth}{NAME}. It's ugly, because it violates encapsulation, and it 
only works because the internal sth has not been ->finished() yet.

Sorry not to have better solutions; I need to think a little bit on this 
and maybe improve the API.

Regards, Laurent D.

**Comment by ialarmedalien** [comment]
Thank you for the suggestions. I'm doing a slight variation of what you suggested by retrieving the current statement arguments (which violates encapsulation, but works well for me!) and then resetting the statement each time I do something that puts the statement into 'refined' status.

i.e.

```
my $args = $stt->{args};
# do some stuff
$stt->reset( %$args );
# do more stuff
```

Maybe adding an official `args` (read only?) method might be useful? Otherwise I am happy committing this small API violation to make my life easier.

Thank you!

**Comment by damil** [comment]
damil commented on 28 May 2017 
> Hum ... I'm afraid the API is not exactly well-suited for your use case. I should probably add some direct accessors for the sth and for the {NAME} attribute.

Have a look at the v3.0 distribution; statements now have new accessors 'sth' and 'headers' , those should suit your needs
